### ISSUE TITLE
"Stop Fishing" equip  Heal Offhand in Tank spec

### ISSUE THREAD

**Issue by fubaWoW** [alarofrunetotem/MrFish#1]
Hi there,

The AddOn will switch only offhand from HealSpec at my Tank spec on Stop Fishing.

This also happens when i just run around and do not fishiing...
This is very annoying!

I've done a little Video to explan what i mean:
https://youtu.be/0A5WHHMWzK0

**Comment by alar77** [comment]
Invited you to the repository.
You can direct work in a branch here then merge to master
To publish on Curse, just make a release 
Happy hacking!
