### ISSUE TITLE
Ability to hide the "Cast fishing" button

### ISSUE THREAD

**Issue by Knaledge** [alarofrunetotem/MrFish#7]
Hello! 

Any chance you'd be willing to add an option to hide (at least) the "Cast Fishing" button? I use MrFish in combination with Fishing Buddy - so I'm able to double-click to recast fishing. Even with one (or all) of the MrFish buttons hidden, I absolutely love (and "need") MrFish's ability to re-equip my weapons after I leave a fishing area/stop fishing. 

I also make occasional use of the "Bait" button because helps in overriding what Fishing Buddy chooses - and why I'd love to be able to optionally show/hide each of the three MrFish buttons. 

I tried my hand at this in a code modification but I apparently broke the "re-equip weapons when leaving fishing area" functionality (one of the main draws to MrFish, for me) (though it still works if I manually click "Stop Casting"). So I figured I'd rather just reach out to you, the expert, for your help since you'd likely be able to accomplish this way (way) faster than me. 

Thank you either way! I love MrFish and have found it super useful over the years. It's absolutely one of my must-install addons.

**Comment by alar77** [comment]
No longer playing wow, I just apply fixes for expansions
